### ISSUE TITLE
Tradução da MedCEP

### ISSUE THREAD

**Issue by vinnysoft** [nemo-ufes/SoMeSPC#3]
A MedCEP está com várias mensagens em inglês devido a utilzação do OpenXava. É necessário terminar a tradução das mensagens por meio dos arquivos i18n/MedCEP-labels_ptBR.properties e MedCEP-messages_ptBR.properties.

**Comment by henribarres** [comment]
A parte de cadastro e os nomes que são apresentados na tela para o usuário estão traduzidos.
Falta verificar a tradução de mensagens de erros que podem eventualmente serem lançadas e demais necessidades.
